{% set version = "4031.107" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-timeseries
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/timeSeries_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/timeSeries/timeSeries_{{ version }}.tar.gz
  sha256: 84386a342af69731024c524f0c28d28a18436b41ae94b9e60fdc67412bdab542

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-timedate >=2150.95

  run:
    - r-base
    - r-timedate >=2150.95

test:
  commands:
    - $R -e "library('timeSeries')"  # [not win]
    - "\"%R%\" -e \"library('timeSeries')\""  # [win]

about:
  home: http://www.rmetrics.org
  license: GPL-2.0-or-later
  summary: Provides a class and various tools for financial time series. This includes basic functions such as scaling and sorting, subsetting, mathematical operations and statistical functions.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
