travis:
  secure:
    BINSTAR_TOKEN: u+N7PUILPeEKr0jLfQIs+tACKrMis8QjCO/jJq8U1mGJ/Uv5NR+zq/4jUPfmSMNC0rydNTpk1Jhi/OL/XfIt7H2fb6hPAHB9uXeFMJZjjNpr0KtZfgWwIy1aBT+yB+RJFxpcVn19iqPWS5/TXvZbR2+QSHnfBj9SrPDunzRcT8YsIzpqaAQ0BklWQBJzGn6vIu0604aMqv6LBYvijDXvMf/UE8e74QMESDJs2C4zExPI+tIFC1B/WoxvNYF/qeOtDIh7XVKgOWNNLRbp5V0LhYQoRHWvy5MxdqXhXuLOGG+veSy4zeP6DEkBL3+39Ioesymqm0z+nEKzHxc351LBNvZ2xPZQKSIAgYjMdASVi1qQxHDqUWUGjxlaghmwllqHiRrXm31NEEhFgoSKklBflIiRvKWg4ophXn0NWvm1cF4DAGipgY/MEYVxwjUe5n4zaRPcNIVuV1hDXcuItwaRBYskEPzYZLGSNEdmYrTcK7wjv5hBQslVt55upRqXwtgjMUpMsoeaxjyaE+ZM8S6ku3/EQRryMZRP0zMk0aypT4QwpPT8f5I89nkwY+cIrBi14koGvCRnIE4Or5L4T7bOZZ3/KzDzuaB9Wv35dYqCDdNPSkRGmoJ4ECyaerP89y9RrWeKNH5djxuZB2XwPiklSXgF22VW8AcVdqiYLFn0MSc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
