travis:
  secure:
    BINSTAR_TOKEN: DPamR00fo9NkVzDL3O0xZlH6fEOo5iSES6aljN+qzNQkXgxk1FIpMEGklDMmLKyt8RW1z70oxShyZzFhay57EM0Vs5Tj1cAXaewcKd6XNaoNTpgTyfCY5e6jOcfnTQBOrQBH1PnLeEiwms01h99c9o8zTpcPbD+OLyhDGdVu6/dLxbpls9eHKBcqXnIXluux8VrJjrcFXRlX5+LHO77LW8pFQei2BQujC+8RBLDfYx99kOZBN/pjvaSisv5Ffu/tC9DexBI73ytc4ATQTLHlzfsVb7t+6l1wJ9vFADyvt1IiY9IOjhB0/ZB6ixT7mKpFpSq8mMGvP8HmDMzX3RshkM6DANYkRyjcQmIiF0yORPPxiXg9mBv25uYBkYMleqX6whk1v3OklAvctXg9hzbzBTxeHGcvnIYhSnZZ+kD3LpN3QqAo7BYC4jrKXPUb40to2TvDpkdXnQtEtVKG37l6qZ6h+POuihnn4TRdSzrKPh/08BCXFFML64u58RnJVqCWOM5TWSfYtSxqzB/lC0Dz2o2bbgImvg2erl0TKudg87cC8FGPp14hbQ7fadBRHy871T858knk1kcoLP6Hy8OSIEXo+AmxCJqsTEiRRduw8zwjQaA35PTFJx1d3a/5+C/o5wsCbQ/A6Lkprkq4nn43j/7M/OA+kqaC9cJ1ZoILUx0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
