appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: w/M4rURHkdMOBpsubBnuY2AaK1bgfwrK2vuJ82E7kJp6iV5lXvOD2eUAmTKT++xWTOZ5pJjMEQ7ye7t/djgH8qn8x1qZPmvcjhPbvK0pstKUkCryQ1U7DS8EvdiHWHKGX5BFpH5jnTj5nm3O+nKAGDAV557S4YwlliGEqLj1VgnSuEdWk/mGNBOVKIizXs5d6cCR3xl/eLEs6jFItTRTxZZVxvbzmDyul/WfAbeZz6r/2t6L3FrJ+UspFvogQpPTnU1Ql4kz3ui2TchrSukOsMLGKjsq76qz2EfoxZKMnuwrECnbLwp6d42xV7hs8f6dmy8EY33pIdkaeLAqvu/QuBHMkM9PL01pFw/Lc4E8fBiContoTVInCNTrRzbjtkeFDmi7vll3U7OH5mV71lP09GhEy7zjRAH3UoVhwJ54rC09YrmC8GLjtL5Ptl3JkZJzDu3v0+z3oYzHKOP5Ew+dcjLXH/TFRKizJVM1Mb8fbM2Okxg8gYKnLPFkXwQVzoP2aSkM3vq1tQn+MQu/U/b9wALpJWMEX7uDEdR5WdZMVA6q8ZrUxr9YRsAMKiQkG99OGhF2D25npw+xZ1n4HOk/CNjveJtEFCscSl0jUnb4moCUL03N9IGSVfmYOxax+hDJ1u/qYlszVP5vzW6X/annnbIG5gJrrpkhqNRambSfeHI=
